[webservers]
web-nginx-php ansible_host=web-nginx-php ansible_user=root ansible_connection=docker

[dbservers]
mysql-db ansible_host=mysql-db ansible_connection=docker

[all:vars]
db_name=usersdb
db_user=labuser
db_pass=labpass
